### ISSUE TITLE
Nix support?

### ISSUE THREAD

**Issue by GirardR1006** [issuu/ocaml-protoc-plugin#47] opened 2023-04-28 09:46 UTC
Hello, I was wondering whether there was a plan to support nix building in the near future? 
I am interested into building a nix package that uses ocaml-protoc-plugin, and I noticed ocaml-protoc-plugin is missing from nixpkgs. 

If there is not time to support nix builds on your side, I could write a nix package for ocaml-protoc-plugin :)

**Comment by andersfugmann** [comment] 2023-04-30 13:43
There are not plans for adding nix support for this package as far as I know, and I don't anticipate this changing soon.
Personally, I have reservation against adding specific packaging instructions to a generic Ocaml project. 
See https://github.com/issuu/ocaml-protoc-plugin/pull/40 for more details and commentary. 

I'm closing the issue as duplicate of https://github.com/issuu/ocaml-protoc-plugin/pull/40 - but only administratively. If you want to discuss this issue more or have further comments, I really encourage you to reopen.

**Closed** 2023-04-30 13:43 UTC

**Comment by GirardR1006** [comment] 2023-08-21 14:21
For the record, since I found the tool really useful, I became the maintainer of its distribution on NixOS: https://search.nixos.org/packages?channel=unstable&show=ocamlPackages.ocaml-protoc-plugin&from=0&size=50&sort=relevance&type=packages&query=ocaml-protoc-plugin

It is not up to date with latest release, I plan to do that when I have the bandwidth.
